import Head from 'next/head'
import { League_Spartan } from 'next/font/google'
import NewInvoice from '@/components/form/NewInvoice'


const inter = League_Spartan({ subsets: ['latin'] })


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NewInvoice/>
      </main>
      
    </>
  )
}
